version: '3'
services:
  frontend:
    image: frontend
    ports:
      - '8080:3334'
  backend:
    image: backend
    ports:
      - '3333:3333'
    environment:
      - DATABASE_URL=postgresql://prisma:prisma@postgres14:5432/prisma?schema=public
  postgres14:
    image: postgres:14
    restart: always
    command: postgres -c 'max_connections=1000'
    volumes:
      - pg_data:/var/lib/postgresql
    environment:
      POSTGRES_USER: "prisma"
      POSTGRES_PASSWORD: "prisma"
      POSTGRES_HOST_AUTH_METHOD: "md5"
      POSTGRES_INITDB_ARGS: "--auth-host=md5"
    ports:
      - "5432:5432"

volumes:
  pg_data:
    external: false
