version: '3'
services:
  frontend:
    image: frontend
    ports:
      - '8080:80'
  backend:
    image: backend
    ports:
      - '3333:3333'
    environment:
      - DATABASE_URL=postgresql://prisma:prisma@postgres14:5432/prisma?schema=public

      - COGNITO_USER_POOL_ID=us-east-1_B4cTzx2oi
      - COGNITO_CLIENT_ID=4fq13t0k4n7rrpuvjk6tua951c
      - COGNITO_REGION=us-east-1

      # mail
      - MAIL_HOST=smtp.gmail.com
      - MAIL_USER=kryptoskode301@gmail.com
      - MAIL_PASSWORD=jsfljoqiswzgpwci
      - MAIL_FROM=kryptoskode301@gmail.com

      # optional
      - MAIL_TRANSPORT=smtp://${MAIL_USER}:${MAIL_PASSWORD}@${MAIL_HOST}
  postgres14:
    image: postgres:14
    restart: always
    command: postgres -c 'max_connections=1000'
    volumes:
      - pg_data:/var/lib/postgresql
    environment:
      POSTGRES_USER: "prisma"
      POSTGRES_PASSWORD: "prisma"
      POSTGRES_HOST_AUTH_METHOD: "md5"
      POSTGRES_INITDB_ARGS: "--auth-host=md5"
    ports:
      - "5432:5432"

volumes:
  pg_data:
    external: false
