name: ci

on:
  push:
    branches:
      - 'develop'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
        #Checking out to the develop branch
      - name: Checkout develop
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

        #Installs node.js
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

        #installs yarn
      - name: Install yarn
        run: npm install yarn -g

      - name: Cache Yarn Packages
        id: cache-yarn-packages
        uses: actions/cache@v2
        with:
          path: ~/.cache
          key: yarn-packages-${{ hashFiles('**/yarn.lock') }}

        #installs the yarn lockfile
      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Build the frontend package and the backend package
        run: yarn nx run-many --target=build --projects=api,office-booker --parallel

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build frontend image
        run: docker build -f ./apps/office-booker/Dockerfile . -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend

      - name: Push frontend image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend

      - name: Build backend image
        run: docker build -f ./apps/api/Dockerfile . -t ${{ secrets.DOCKERHUB_USERNAME }}/backend

      - name: Push backend image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend
